Jdp221202 1
piotr-grosicki/project-jdp-2212-02 pull request #18
Opened 2022-12-05 22:21 UTC by osklie

2022-12-08 22:10 UTC, osklie commented on src/main/java/com/kodilla/ecommercee/domain/ProductDt.java
> +public class ProductDt {
nie wnosilem do dto zadnych poprawek to stworzylem dodatkowo i zakomitowalem przypadkowo. juz usuwam.

2022-12-08 23:04 UTC, Skila93 commented on build.gradle
> +    implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.4.0-b180830.0359'
Czy to nam potrzebne?

2022-12-10 12:44 UTC, Skila93 requested changes
Zgodnie ze schematem powinieneś mieć relację Many to many nie tylko z Cart ale też z Order

2022-12-10 14:23 UTC, Skila93 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +//public class CartService {
Jeśli masz to całe zakomentowane, to po co to dodajesz?

2022-12-12 00:28 UTC, Skila93 reviewed
Ogólnie chyba ok tylko czy mógłbyś zrobić pull request tylko klasy którą dodajesz, czyli Product?

2022-12-12 06:19 UTC, osklie commented
@Skila93 tak wlasnie robie, co jest za duzo?

2022-12-12 09:08 UTC, closed without merging