Jdp221202 4
piotr-grosicki/project-jdp-2212-02 pull request #4
Opened 2022-11-21 20:07 UTC by lukisek88

2022-11-21 22:19 UTC, piotr-grosicki requested changes

2022-11-21 22:19 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +@Service
to nie jest service

2022-11-21 22:19 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/shop?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
tego nie mozna usuwac

2022-11-21 22:19 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False
tego nie mozna zmieniac w testowych resourcach

2022-11-21 22:21 UTC, piotr-grosicki requested changes
konflikty

2022-11-22 05:39 UTC, lukisek88 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +@Service
Poprawione

2022-11-22 05:40 UTC, lukisek88 commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:mysql://localhost:3306/shop?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
Poprawione

2022-11-24 08:03 UTC, merged